["enry.sourced.tech"]
  repository = "src-d/enry"
  min-version = "v1.5.2"

["go-siva.sourced.tech"]
  repository = "src-d/go-siva"
  min-version = "v1.1.3"

["bblf.sh"]
  repository = "bblfsh/bblfshd"
  min-version = "v2.1.1"
